export const BUTTON_TYPES = {
	PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  TERTIARY: 'TERTIARY',
	OUTLINE: 'OUTLINE',
  LINK: 'LINK',
}

export const NAV_ITEM_TYPES = {
	LINK: 'LINK',
	BUTTON: 'BUTTON',
	DROP_DOWN: 'DROP_DOWN',
	LOGO: 'LOGO'
}

export const SECTION_TYPES = {
	HERO_SECTION: 'HERO_SECTION',
	TWO_CALL_TO_ACTION: 'TWO_CALL_TO_ACTION',
	WITH_CARDS: 'WITH_CARDS',
	MULTIPLE_MEDIA_WITH_CAPTION: 'MULTIPLE_MEDIA_WITH_CAPTION',
	SINGLE_MEDIA_WITH_CAPTION_AND_PARAGRAPH:
		'SINGLE_MEDIA_WITH_CAPTION_AND_PARAGRAPH',
	SINGLE_MEDIA_WITH_PARAGRAPH_AND_LINK: 'SINGLE_MEDIA_WITH_PARAGRAPH_AND_LINK',
	HEADING_WITH_SINGLE_MEDIA_AND_BUTTON: 'HEADING_WITH_SINGLE_MEDIA_AND_BUTTON',
	REPORTS: 'REPORTS',
  CONTACT_BANNER: 'CONTACT_BANNER',
  SUPPORT_CARD: 'SUPPORT_CARD',
  BLOG_POST: 'BLOG_POST',
  FEATURE_PRICING_CARD: 'FEATURE_PRICING_CARD',
  FEATURE_CARD: 'FEATURE_CARD',
  WITH_ACCORDION: 'WITH_ACCORDION',
  STAFF_MEMBER: 'STAFF_MEMBER',
  CONTACT_FORM: 'CONTACT_FORM',
  STATIC: 'STATIC',
  PLUGIN: 'PLUGIN',
  COLLATERAL_CARD: 'COLLATERAL_CARD',
  CALENDAR_CARD: 'CALENDAR_CARD',
  BLOG_HOME: 'BLOG_HOME',
  REQUEST_ACCESS_CODE: 'REQUEST_ACCESS_CODE'
}

export const CARD_TYPES = {
	FEATURE_CARD: 'FEATURE_CARD',
	SUPPORT_CARD: 'SUPPORT_CARD'
}
